### PR TITLE
Remove pandoc

### PR DESCRIPTION
**Pull request by TheLillo**
Use the official [Pandoc](https://packages.ubuntu.com/search?keywords=pandoc) Ubuntu package instead of download it in a manual and not maintainable way

### CODE REVIEW

**Comment by lucat1** [comment]
This is requried as the ubuntu's package is a few minor releases behind and it doesn't provide a feature or bug fix (I really can't recall what it was) needed for one of our repos.
Before this issue came up we were in fact using the package provided by ubuntu.
Here's the commit which introduced this: csunibo/template@0498fbde4a6fc061709ad914fbe6eba0ed9fa56b

**Comment by TheLillo** [comment]
Luckily for this project it works :)

**Comment by lucat1** [comment]
Surely it does work, it's not used in the action. It was used at first to convert md to tex but now the script generates tex on its own so that's just a leftover (and I'd be happy to approve this request were it to remove the dependency entirely).

Eitherway, this change in all other repos would result in [this error](https://github.com/csunibo/linguaggi-di-programmazione/runs/6290638818?check_suite_focus=true) (yes I've dug and found it).
The error comes from pandoc changing the name of the flag we're using as also noted [here](https://github.com/typora/typora-issues/issues/2146#issuecomment-462073512).
Back when the action were written (and as of this day, until ubuntu updates the package) we had two options:
- Change our flag to comply with the older version of pandoc: this makes us dependent on the ubuntu repository release schedule as when they decide to update the package all our actions will be broken and will require immediate intervention.
- Manually download a newer version of pandoc: this also adds a dependency for somebody in the future to check whether ubuntu has updated the package and apply the suggested patch. Contrary to the previous method the dependency caused by this one doesn't require immediate intervention.

The reason we went with the latter was to remove some burden from the maintainers, albeit using a sub-optimal solution.
One final minor benefit to note is that we're using a slightly-newer version of pandoc with (hopefully) more features or fixes.

**Comment by TheLillo** [comment]
I think that keep separate other project from this one could be a better design choice. Maybe you can use the other manual approach where you need it and keep this one automatic

**Comment by FoxySeta** [comment]
> Surely it does work, it's not used in the action.

Hi @TheLillo, as @lucat1 correctly stated, the `pandoc` dependency is installed but never actually used by this project. That was a silly mistake of mine: @giammirove's repo worked with Markdown files, but our fork doesn't, so we don't need a Markdown converter in the first place.

In other words, this dependency should be removed (possibly by this PR, since it raised this concern). Of course, without `pandoc` around, there won't be any need to debate the best way to install it.

**Review by FoxySeta — CHANGES_REQUESTED** [review]
At this point, not only the "Install format conversion tools" should be removed, but `pandoc` should not be installed in the first place.

**Comment by TheLillo** [comment]
Hi, you are right! I was wrong. I thought Pandoc was needed elsewhere. I delete the dependency

**Review by FoxySeta — APPROVED** [review]

**Comment by FoxySeta** [comment]
Thanks! Merged it right away.

**Pull request merged**
